# Introduction to python
In this session we will cover some basic aspects of Python using Jupyter notebooks.

1. Syntax
2. Data types
3. Loops and control structures
4. numpy, scipy, math

The content of this section was partially taken from https://github.com/cuttlefishh/python-for-data-analysis/blob/master/lessons/lesson04.ipynb

## Syntax

In [5]:
2 / 5

0.4

In [6]:
x = 5
y = 2
x * y

10

In [7]:
x ** y

25

In [12]:
6 ** 9

10077696

In [9]:
print('Hello Lao PDR!')

Hello Lao PDR!


In [10]:
print(x)

5


In [14]:
print(' Variable x is %s' %(x))

 Variable x is 5


In [13]:
print('%s raised to power of %s equals %s' % (x, y, x ** y))

5 raised to power of 2 equals 25


# Data Types
## Booleans

'True' and 'False' have special meaning in Python.

In [15]:
a = True
b = False
c = True

In [17]:
a == True

True

In [27]:
a != True

False

In [18]:
b == True

False

In [22]:
x == 6

False

In [23]:
a or b

True

In [24]:
a and b

False

In [26]:
a or b or c

True

## Numbers: integers and floats

Numbers are pretty straightforward, especially in Python 3.

In [28]:
1 + 2

3

In [29]:
1.0 + 2.0

3.0

In [30]:
1 / 2

0.5

In [31]:
1.0 / 2.0

0.5

In [32]:
type(1)

int

In [33]:
type(1/2)

float

Division residual

In [34]:
4 / 2

2.0

In [1]:
4 % 2

0

In [36]:
5/3

1.6666666666666667

In [35]:
5 % 3

2

## Strings

The next four data types -- strings, lists, tuples, arrays -- are all sequences.

Strings are sequences of characters.

In [37]:
s = 'Hello, world'

In [38]:
type(s)

str

In [41]:
s[0:4]

'Hell'

In [42]:
s + '!'

'Hello, world!'

In [44]:
s

'Hello, world'

In [45]:
s = s + '!'

In [46]:
s

'Hello, world!'

In [47]:
len(s)

13

## Lists

Lists are mutable sequences of anything.

In [48]:
l = [0, 1, 1, 2, 3, 5, 8]

In [49]:
m = [5, 2, 'a', 'xxx', True, [0, 1]]

In [50]:
l[0:3]

[0, 1, 1]

In [52]:
m[4]

True

In [53]:
m[4] = False

In [56]:
m[4:]

[False, [0, 1]]

## Tuples

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [57]:
n = (3, 5, 6)

In [58]:
n[0]

3

In [59]:
n[0] = 2

TypeError: 'tuple' object does not support item assignment

In [60]:
n = (2, 5, 6)

## Arrays (numpy)

In [61]:
# Import modules to use
import math
import numpy as np

In [62]:
mylist = [0, 2, 4]
np.array(mylist)

array([0, 2, 4])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [67]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [68]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [69]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [70]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [71]:
np.random.rand()

0.9141049700696346

In [72]:
np.random.rand(5)

array([0.19983761, 0.79446657, 0.64275686, 0.2716169 , 0.49713807])

## Sets

Sets are unordered collections of unique objects.

In [73]:
s1 = {'a', 'b', 'c'}
s2 = {'a', 'd', 'e'}

In [74]:
s1 & s2

{'a'}

In [75]:
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [76]:
s3 = set(l)
s4 = set(m[0:2])

In [80]:
s3

{0, 1, 2, 3, 5, 8}

In [78]:
s4

{2, 5}

In [79]:
s3 & s4

{2, 5}

In [81]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [82]:
s3 - s4

{0, 1, 3, 8}

## Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [83]:
d = {'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [84]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [85]:
d['name']

'John Doe'

In [86]:
d['zip'] = 92039

In [87]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989', 'zip': 92039}

# Loops and Control Structures
## Boolean and comparison operations

In [88]:
x = 5
(x < 6) and (x > 4)

True

In [89]:
x != 4

True

In [90]:
5 in [3, 4, 5]

True

In [92]:
'ell!' in 'Hello'

False

In [93]:
len('Hello') >= 5

True

## if tests

In [96]:
if 'd' in 'abc':
    print('Learn your alphabet.')

In [98]:
x = 5
y = 5
if x == y:
    print('Same number')
else:
    print('Different number')

Same number


In [99]:
if 'd' in 'abc':
    print('Learn your alphabet.') 
elif (2 + 2 == 5):
    print('Sometimes yes.')
else: 
    print('Nothing is true.')    

Nothing is true.


## while loops

In [103]:
i = 0
while (i < 5):
    print(i)
    i += 1
    print('Added one to {0}'.format(i))

0
Added one to 1
1
Added one to 2
2
Added one to 3
3
Added one to 4
4
Added one to 5


In [104]:
i

5

## for loops

In [105]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


In [ ]:
for x, y in zip([2,5,6,8], [6,8,9,11]):
    print(x*y)

# Determining Your Python Version
## Method 1: sys

In [ ]:
import sys

In [ ]:
sys.version

In [ ]:
'3.7.0 | packaged by conda-forge | (default, Aug 27 2018, 17:24:52) \n[Clang 6.1.0 (clang-602.0.53)]'

## Method 2: platform

In [ ]:
import platform

In [ ]:
platform.python_version()

In [ ]:
platform.version()

## Method 3: version_information

In [ ]:
# first install: pip install version_information
%reload_ext version_information
%version_information math, numpy, sys, platform